channels:
    - pytorch
    - main
    - nvidia
    - conda-forge

dependencies:
    - pytorch==1.7.1=py3.9_cuda11.0.221_cudnn8.0.5_0
    - cudatoolkit=11
    - torchvision==0.8.2
    - flask>=1.1
    - tqdm
    - pip
    - requests

    - pip:
        - ftfy
        - regex
