channels:
    - pytorch
    - main
    - nvidia
    - conda-forge

dependencies:
    - pytorch-cuda=11.8
    - flask>=1.1
    - tqdm
    - pip
    - requests

    - pip:
        - ftfy
        - regex
